<a href="https://colab.research.google.com/github/polock11/TensorFlow/blob/main/00_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Topics Covered
* Intro
* Getting info from tensors
* Manipulation tensors
* Using @tf.fuction
* Using GPU's

#Definitions
* Scalar: a scalar is a single number
* Vector: a vector is a number with direction
* Matrix: a matrix is a 2 diemnsional arry of numbers
* Trnsor: a tensor is a n-dimensional arry of numbers (n can be any positive number)

#I16

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#creating tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check dimension
scalar.ndim

0

In [ ]:
#create vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create matrix
matrix = tf.constant([
    [10,3,5],
    [4,89,3]
])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  3,  5],
       [ 4, 89,  3]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([
        [10., 7.],
        [4., 5.],
        [6., 9.]
], dtype= tf.float16)

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 4.,  5.],
       [ 6.,  9.]], dtype=float16)>

In [ ]:
# creating a 3 dimensional tensor

tensor = tf.constant([
    [[1,2,3],
     [4,5,6]],
    [[3,4,5],
     [2,5,8]],
    [[4,5,6],
     [2,3,5]]
])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[3, 4, 5],
        [2, 5, 8]],

       [[4, 5, 6],
        [2, 3, 5]]], dtype=int32)>

# I17

In [ ]:
changable_tensor = tf.Variable([1,2,4])
unchangable_tensor = tf.constant([3,4,5])

In [ ]:
changable_tensor[0].assign(6)
changable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([6, 2, 4], dtype=int32)>

In [ ]:
unchangable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#I18

In [ ]:
 # creating random tensors

random_1 = tf.random.Generator.from_seed(43)
random_1 = random_1.normal(shape=(3,4,3))
#random_1

random_2 = tf.random.Generator.from_seed(43)
random_2 = random_2.normal(shape=(3,4,3))

random_3 = tf.random.Generator.from_seed(43)
random_3 = random_3.normal(shape=(3,4,3))

In [ ]:
random_1 == random_2
random_2 == random_3

<tf.Tensor: shape=(3, 4, 3), dtype=bool, numpy=
array([[[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])>

In [ ]:
# https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [ ]:
k = tf.random.normal(shape=(3,3,2), mean=0, stddev=5)
i = tf.random.uniform(shape=(3,3,3), minval=0, maxval=10, dtype=tf.int32)

#I19

* Shuffle tensors

In [ ]:
tensor_x = tf.random.uniform(shape=(3,3,3), minval= 5, maxval=10, dtype=tf.int32)
tensor_x

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[5, 5, 9],
        [8, 9, 5],
        [5, 8, 7]],

       [[8, 5, 8],
        [5, 6, 5],
        [8, 6, 7]],

       [[5, 8, 6],
        [8, 6, 5],
        [9, 8, 6]]], dtype=int32)>

In [ ]:
shuffled_tensor = tf.random.shuffle(tensor_x)
shuffled_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[5, 5, 9],
        [8, 9, 5],
        [5, 8, 7]],

       [[8, 5, 8],
        [5, 6, 5],
        [8, 6, 7]],

       [[5, 8, 6],
        [8, 6, 5],
        [9, 8, 6]]], dtype=int32)>

#I20

In [ ]:
ones = tf.ones((10,7), dtype=tf.int32)
ones

<tf.Tensor: shape=(10, 7), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1]], dtype=int32)>

* The difference between a tensor and numpy array is tensor can run on GPU


In [ ]:
# convert numpy array to tensor

import numpy as np

np_array = np.arange(1,25, dtype=np.int32)
np_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
h = tf.constant(np_array, shape=(3,2,4))
h

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

#I21

In [ ]:
#gettting information from tensors

xx = tf.random.uniform(shape=(2,3,4,5), minval=0, maxval=(10), dtype=tf.int32)
xx

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[7, 7, 1, 2, 3],
         [8, 4, 1, 2, 5],
         [0, 5, 9, 2, 8],
         [6, 7, 6, 4, 1]],

        [[3, 1, 4, 6, 7],
         [7, 1, 0, 1, 5],
         [3, 9, 5, 9, 3],
         [6, 3, 5, 0, 6]],

        [[6, 2, 1, 6, 5],
         [7, 8, 9, 4, 8],
         [5, 1, 8, 1, 7],
         [0, 2, 3, 0, 2]]],


       [[[0, 9, 2, 1, 6],
         [5, 1, 4, 2, 8],
         [0, 7, 2, 9, 0],
         [2, 9, 2, 6, 4]],

        [[3, 3, 1, 4, 8],
         [0, 4, 9, 9, 5],
         [2, 5, 7, 6, 8],
         [2, 2, 9, 5, 0]],

        [[0, 9, 4, 7, 3],
         [9, 6, 6, 2, 2],
         [8, 9, 6, 5, 6],
         [9, 2, 8, 0, 2]]]], dtype=int32)>

In [ ]:
xx.shape, xx.ndim, tf.size(xx)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
dtype = f'Data type of tensor elements:{xx.dtype}'
shape = f'Shape of the tensor is: {xx.shape}'
elem = f'Total elements of the tensor: {tf.size(xx).numpy()} '
ndim = f'Number of Dimensions: {xx.ndim}'
elem_1st = f'Element of 1st index:{xx.shape[0]}'
elem_last = f'Element of 1st index:{xx.shape[-1]}'


In [ ]:
print(dtype)
print(shape)
print(elem)
print(ndim)
print(elem_1st)
print(elem_last)

Data type of tensor elements:<dtype: 'int32'>
Shape of the tensor is: (2, 3, 4, 5)
Total elements of the tensor: 120 
Number of Dimensions: 4
Element of 1st index:2
Element of 1st index:5


#I21

In [ ]:
# indexing tensors

a =tf.ones(shape=(4,4,4,4), dtype=tf.int32)
a

<tf.Tensor: shape=(4, 4, 4, 4), dtype=int32, numpy=
array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

    

In [ ]:
#get first 2 elements
a[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int32)>

In [ ]:
#a[:,:,:,:]

a[:1,:,:,:]

<tf.Tensor: shape=(1, 4, 4, 4), dtype=int32, numpy=
array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]], dtype=int32)>

In [ ]:
rank_2 = tf.constant([[1,2,3],[4,5,6]])
rank_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6], dtype=int32)>

In [ ]:
# adding dimesion to the tensor

rank_3 = rank_2[..., tf.newaxis]
rank_3

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

In [ ]:
# alternativa way

tf.expand_dims(rank_2, -1) # -1 means expand after the last axis, more like how an index works

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)>

#I22 Tensor Operations

In [ ]:
a = tf.random.uniform(shape=(4,3), minval=1, maxval=4, dtype=tf.int32)
b = tf.random.uniform(shape=(4,3), minval=5, maxval=6, dtype=tf.int32)
a,b

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[3, 3, 2],
        [1, 1, 2],
        [2, 1, 3],
        [2, 1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]], dtype=int32)>)

In [ ]:
tf.add(a,b)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[8, 8, 7],
       [6, 6, 7],
       [7, 6, 8],
       [7, 6, 7]], dtype=int32)>

In [ ]:
tf.subtract(a,b)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[-2, -2, -3],
       [-4, -4, -3],
       [-3, -4, -2],
       [-3, -4, -3]], dtype=int32)>

In [ ]:
tf.multiply(a,b)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[15, 15, 10],
       [ 5,  5, 10],
       [10,  5, 15],
       [10,  5, 10]], dtype=int32)>

In [ ]:
tf.math.divide(b,a)

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[1.66666667, 1.66666667, 2.5       ],
       [5.        , 5.        , 2.5       ],
       [2.5       , 5.        , 1.66666667],
       [2.5       , 5.        , 2.5       ]])>

In [ ]:
a = tf.random.uniform(shape=(4,3), minval=1, maxval=4, dtype=tf.int32)
b = tf.random.uniform(shape=(3,4), minval=10, maxval=20, dtype=tf.int32)
a,b

(<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
 array([[1, 2, 1],
        [1, 1, 2],
        [1, 2, 1],
        [1, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[19, 14, 19, 13],
        [13, 18, 10, 17],
        [10, 12, 18, 19]], dtype=int32)>)

In [ ]:
tf.matmul(a,b)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 55,  62,  57,  66],
       [ 52,  56,  65,  68],
       [ 55,  62,  57,  66],
       [ 88, 104, 103, 121]], dtype=int32)>

#I26


In [ ]:
#matrix multiplication and dot product is the same this. can be done by tf.matmul and tf.tensordot

In [ ]:
tf.cast(a,tf.float32)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 2., 1.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 3., 3.]], dtype=float32)>

#I28
tensor aggregation

In [ ]:
a = tf.random.uniform((5,5,2),-100,100, tf.int32)

In [ ]:
a

<tf.Tensor: shape=(5, 5, 2), dtype=int32, numpy=
array([[[-66, -87],
        [-97,  44],
        [ 54,  46],
        [ 98, -68],
        [ 35,  94]],

       [[ 64,  18],
        [ 49,  45],
        [-46, -22],
        [-50,   8],
        [ 52,  57]],

       [[-92,  43],
        [-62, -69],
        [-19,  22],
        [-18, -78],
        [ 30, -18]],

       [[-62,  90],
        [-13, -68],
        [-64, -74],
        [-79,  39],
        [  5,  15]],

       [[ 59,  61],
        [-92,   9],
        [ 29, -75],
        [ 24,  62],
        [ 30,  36]]], dtype=int32)>

In [ ]:
tf.reduce_min(a).numpy()

-97

In [ ]:
tf.reduce_max(a).numpy()

98

In [ ]:
tf.reduce_sum(a).numpy()

-101

In [ ]:
tf.reduce_mean(a).numpy()

-2

In [ ]:
import tensorflow_probability as tfp

tfp.stats.variance(a)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[4472, 3687],
       [3008, 2625],
       [1981, 2413],
       [3824, 3172],
       [ 226, 1432]], dtype=int32)>

In [ ]:
tf.math.reduce_std(tf.cast(a, dtype=tf.float32)).numpy()

57.078014

#I30

In [ ]:
a = tf.random.uniform(shape=(50,))
a

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.08768284, 0.74540865, 0.46303844, 0.14600766, 0.561772  ,
       0.81475127, 0.18903613, 0.5560175 , 0.04541171, 0.62687063,
       0.4405023 , 0.9856678 , 0.49009693, 0.24487984, 0.9664035 ,
       0.92918646, 0.06977832, 0.03811133, 0.38063312, 0.5637702 ,
       0.9253726 , 0.46238363, 0.34515905, 0.3612827 , 0.29746342,
       0.00248539, 0.08106339, 0.5953771 , 0.30756843, 0.7440295 ,
       0.9974184 , 0.03821397, 0.8739848 , 0.9444525 , 0.5707704 ,
       0.8002852 , 0.8174851 , 0.75485694, 0.2705642 , 0.19348502,
       0.93062365, 0.80915177, 0.22638845, 0.5953282 , 0.6443833 ,
       0.42809117, 0.7325579 , 0.98225677, 0.00268722, 0.07721317],
      dtype=float32)>

In [ ]:
tf.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=30>

In [ ]:
a[tf.argmax(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9974184>

In [ ]:
tf.argmin(a)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [ ]:
a[tf.argmin(a)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0024853945>

In [ ]:
b= tf.random.uniform(shape=(3,3,3), minval = 1, maxval=9, dtype=tf.int32)
b

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[5, 1, 3],
        [2, 7, 8],
        [2, 7, 2]],

       [[7, 2, 1],
        [5, 4, 7],
        [2, 8, 3]],

       [[6, 6, 3],
        [8, 5, 4],
        [3, 2, 8]]], dtype=int32)>

In [ ]:
tf.argmax(b)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 0],
       [2, 0, 0],
       [2, 1, 2]])>

#I31


In [ ]:
#tensor flow squeeze
tf.random.set_seed(42)
a = tf.constant(tf.random.uniform(shape=[50,]), shape=(1,1,1,1,50))
a

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(a) #removes all the single dimensions from the tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

#I32

In [ ]:
#one hot encode tensor

some_list = [3,1,3,4,5]
tf.one_hot(some_list, depth=6)

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#sqaring, sqrt,log

x=tf.range(1,10)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(x)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(x, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# ternsorflow and numpy
import numpy as np

x = tf.constant(np.arange(1,10))

x.numpy(), type(x.numpy())

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [ ]:
np.array(x), type(np.array(x))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [ ]:
#Finding GPU access

tf.config.list_physical_devices()
#tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Mon Jun 17 09:33:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0              29W /  70W |    103MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
#1
scalar = tf.constant(5)

vector = tf.constant([12,3,4,5,6,73,6,6])

matrix = tf.constant([[1,2,3,4],
                      [2,3,41,4],
                      [23,5,6,3]])

tensor = tf.constant(
    [[[12,4,5],
    [23,43,1],
    [8,57,4]],


    [[12,43,7],
    [67,8,3],
    [2,4,6]]]
)

In [ ]:
#2

def get_info(x):
    return x.shape, x.ndim, tf.size(x).numpy()


scalar_shape, scalar_dim, scalar_size = get_info(scalar)
vector_shape, vector_dim, vector_size = get_info(vector)
tensor_shape, tensor_dim, tensor_size = get_info(tensor)
matrix_shape, matrix_dim, matrix_size = get_info(matrix)


#matrix_shape, matrix_dim, matrix_size

(TensorShape([3, 4]), 2, 12)

In [ ]:
#3

tf.random.set_seed(42)

tensor_a = tf.random.uniform((5,300), 0,1)
tensor_b = tf.random.uniform((5,300), 0,1)

In [ ]:
#4

res = tf.matmul(tensor_a, tf.transpose(tensor_b))

In [ ]:
#5

res_dot = tf.tensordot(tensor_a, tf.transpose(tensor_b),1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.333435, 73.40498 , 77.15961 , 73.98368 , 80.90053 ],
       [75.14637 , 68.80438 , 74.24303 , 71.84184 , 75.60205 ],
       [79.7594  , 75.64456 , 77.79758 , 74.748726, 80.55984 ],
       [75.085266, 69.06408 , 74.30776 , 72.27615 , 76.05667 ],
       [85.05689 , 74.26629 , 78.00687 , 74.886795, 83.13417 ]],
      dtype=float32)>

In [ ]:
#6
tf.random.set_seed(23)

tensor_c = tf.random.uniform([224,224,3], 0,1)

In [ ]:
#7
tf.reduce_max(tensor_c[0]), tf.reduce_min(tensor_c[0])

(<tf.Tensor: shape=(), dtype=float32, numpy=0.99957156>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0025897026>)

In [ ]:
#8

tensor_x = tf.random.uniform([1,224,224,3], 0,1)
tensor_x_squeezed = tf.squeeze(tensor_x)

tensor_x_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.9929017 , 0.6378733 , 0.335773  ],
        [0.4006816 , 0.7837721 , 0.89023626],
        [0.7642853 , 0.19973111, 0.73868346],
        ...,
        [0.2780851 , 0.06537044, 0.6527029 ],
        [0.03169656, 0.58649504, 0.67114484],
        [0.24005389, 0.510761  , 0.1086185 ]],

       [[0.18847585, 0.8783175 , 0.9365133 ],
        [0.5454662 , 0.37045264, 0.19518054],
        [0.41947842, 0.00910306, 0.996048  ],
        ...,
        [0.66999614, 0.688213  , 0.07078707],
        [0.95243216, 0.43373907, 0.8887682 ],
        [0.36297143, 0.35791862, 0.5512918 ]],

       [[0.9148817 , 0.9590056 , 0.26632833],
        [0.88720274, 0.8975265 , 0.62623966],
        [0.42320168, 0.02778387, 0.7122961 ],
        ...,
        [0.15505147, 0.47819436, 0.16151476],
        [0.6922122 , 0.28036702, 0.60562265],
        [0.28843772, 0.14054227, 0.30630243]],

       ...,

       [[0.8339411 , 0.31764746, 0.7197784 ],
        [0.01

In [ ]:
#9
t = tf.range(0,10)

tf.argmax(t)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [ ]:
#10
tf.one_hot(t, depth = 9)

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>